export const HomePhotoCardData = [
  {
    id: 1,
    to: `/`,
    img: `/Media/Home/9.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
  {
    id: 2,
    to: `/`,
    img: `/Media/Home/10.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
  {
    id: 3,
    to: `/`,
    img: `/Media/Home/11.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
  {
    id: 4,
    to: `/`,
    img: `/Media/Home/12.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
  {
    id: 5,
    to: `/`,
    img: `/Media/Home/13.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
  {
    id: 6,
    to: `/`,
    img: `/Media/Home/12.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`hidden`,
  },
];

export const HomePhotoCardData2 = [
  {
    id: 1,
    to: `/`,
    img: `/Media/Home/9.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
  {
    id: 2,
    to: `/`,
    img: `/Media/Home/10.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
  {
    id: 3,
    to: `/`,
    img: `/Media/Home/11.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
  {
    id: 4,
    to: `/`,
    img: `/Media/Home/12.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
  {
    id: 5,
    to: `/`,
    img: `/Media/Home/13.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
  {
    id: 6,
    to: `/`,
    img: `/Media/Home/12.jpeg`,
    title: `Beginners Workshop`,
    paraClass:`pb-[2rem]`,
    desc: `We at DPC organize variety of workshops to meet your creative requirements and move ahead. So what are you waiting for ? Join now to experience.`,
  },
];
